---
# file: tasks/install.yml
# https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1

- name: Install packages to use a repository over https
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Add docker's official gpg key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install docker-ce
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-compose
